name: Run RSpec Suite

on:
  push:
    branches: [trunk]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        # https://github.com/ruby/setup-ruby/releases/tag/v1.194.0
        uses: ruby/setup-ruby@c04af2bb7258bb6a03df1d3c1865998ac9390972
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rspec
